### ISSUE TITLE
Closing W3C-DVCG (Digital Verification Community Group)

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/community#105]
Most of the repositories from the now-inactive task force W3C-DVCG (Digital Verification Community Group) have been copied to the W3C Credentials CG repo.

However, the copied repositories are still there (and don't seem to redirect) and there are some repositories that are not planned to be moved.

* [x] We need some form closure/deprecation or forward or notice for those repos that have been copied.
* [x] The W3C page for DVCG need update.
* [x] If people want the non-moved repos to move to their personal repos, they should do so now.
* [x] The DVCG github home page needs changes that the DVCG and repos are are closed, and point people to the correct places.
* [x] Update DVCG at W3C Wordpress Site
* [x] We should formally close the DVCG with the W3C-Staff. Note to Ivan?

-- Christopher Allen

**Comment by ChristopherA** [comment]
@dmitrizagidulin You've been working some on this. Could you share your thoughts and progress?

**Comment by kimdhamilton** [comment]
if you want to contribute, either mark to archive it or propose where it should be moved

**Comment by jandrieu** [comment]
One problem is that many of the URLs in the repos still point to the old address.

**Comment by OR13** [comment]
See: https://github.com/w3c-ccg/w3c-ccg.github.io/issues/1

URLS can be fixed, but honestly... a broken URL is a valuable way of communicating that something is not important enough to update... which in the case of anything cryptography related is pretty serious indication of unusable / not to be recommended at all status....

I have opened issues on all remaining repos in the W3C DVCG.

In 1 month, if they have not been moved or fixed as is the case for these: https://github.com/w3c-dvcg/ld-proofs

or https://w3c-ccg.github.io/lds-ecdsa-secp256k1-2019/

or at this point, if it never made it into the https://w3c-ccg.github.io/ld-cryptosuite-registry/#introduction

it should simply be archived...

Heads up, a lot of the remaining items are contributed to / solely contributed to be @msporny

The DVCG should have clear language on its website indicating its expired status... any repos which remain should have clear warning to not be used (Archived achieves this when no response is given by contributors).... we are pretty close to wrapping this up, lets get it finished.

**Comment by dmitrizagidulin** [comment]
I think we should first move them to the CCG org, and _then_ archive the ones that need it.
I'd move them, but I don't have the admin access.
Can one of the admins just move all the remaining repos to the CCG org?

**Comment by OR13** [comment]
I agree, if made an admin of the dvcg, I would do this.

**Comment by ChristopherA** [comment]
I have sent a GitHub invite to @OR13 to have "owner" permissions in this community so that we can archive and retire it appropriately.

-- Christopher Allen

**Comment by OR13** [comment]
@ChristopherA https://github.com/w3c-dvcg/w3c-dvcg.github.io/pull/2

^ this and the last item in the checklist are all that remain.

**Comment by kimdhamilton** [comment]
Action for chairs: formally close the DVCG with the W3C-Staff.

**Comment by kimdhamilton** [comment]
@msporny note that the billing email for the DVCG org is still going to Digital Bazaar and Christopher can't change it. Just FYI

**Comment by msporny** [comment]
> @msporny note that the billing email for the DVCG org is still going to Digital Bazaar and Christopher can't change it. Just FYI

What is the action for me here? Change it to another email address? If so, which one?

**Comment by kimdhamilton** [comment]
no action -- Christopher just wanted to make sure you weren't being billed. Why I'm in the middle of this? No clue.

**Comment by kimdhamilton** [comment]
Chairs to move forward

**Comment by ChristopherA** [comment]
@jandrieu Send note to Ivan at W3C to close.

**Comment by jandrieu** [comment]
Note sent.

**Comment by kimdhamilton** [comment]
See Ivan's response below. I think it's ok to close, because we decided to do exactly what he described below.

From Ivan:
The Community Group, at least on W3C's side, has already been closed a while ago. Look at

https://www.w3.org/community/digital-verification/

where it says:

> closed on 2019-08-13 - see the Credentials Community Group instead.

This also means that all the mailing lists have been closed, too. Ie, I have nothing to do:-)

For the repos, it is a different problem (these are not managed by W3C). As far as I can see the cg's repositories were under the w3c-dvcg organization in github. I have no particular access to the w3c-dvcg organization; I only have admin rights to the w3c and the ccg organizations (the latter is because Many put me as an admin when I joined you guys). Transferring ownership, I presume, would require admin rights on both sides.

That being said, something has already been done. I see, on the

https://w3c-dvcg.github.io/

site a number of repository references. The first one, namely

https://w3c-dvcg.github.io/ld-signatures/

has been transferred to

https://w3c-ccg.github.io/ld-proofs/

and github is good to redirect such URL-s. Ie, that one is settled. However, all the other repositories have been archived instead of being transferred. For example, I have found

https://github.com/w3c-dvcg/http-signatures-audit

which says it has been archived and refers to

https://github.com/w3c-ccg/http-signatures-audit

You an see all the relevant repositories here:

https://github.com/w3c-dvcg

I of course do not know who decided on these and who did it, but I do not think it is a good idea to change this now; the repositories have probably evolved since.

I think that is the maximum I can do...

**Comment by OR13** [comment]
close it!

**Comment by kimdhamilton** [comment]
Closing per June 2 discussion
