### ISSUE TITLE
Multibase/multihash/hashlink status

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#133]
These are expired IETF drafts.
Do they need to be resent? Do we need to track in CCG?

also, multihash link isn't current: https://w3c-ccg.github.io/multihash/index.xml

**Comment by ChristopherA** [comment]
If any of these have been accepted as a work item in an IETF WG, I'd like to see that a tagged draft of these be added as a CCG Final Report so that we can add to our "brag" list our success in incubating a document into the next level of standards process and organization.

If these will not no longer be accepted as IETF items, and progress is not being made on them here (as a lot of this work is happening in the IPFS community), we should close these as formal work items of the CCG.

-- Christopher Allen

**Comment by msporny** [comment]
I have updated and published two new drafts at IETF to refresh the specs and mark them as "alive":

https://datatracker.ietf.org/doc/draft-multiformats-multihash/
https://datatracker.ietf.org/doc/draft-multiformats-multibase/

The hashlink spec had been updated/published about a month ago.

**Comment by kimdhamilton** [comment]
Excellent, thanks Manu. Closing this
