### ISSUE TITLE
Finish documenting CCG process

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#138]
For example, we want to revise requirements for community notes being completed. https://docs.google.com/document/d/1vj811aUbs8GwZUNo-LIFBHafsz4rZTSnRtPv7RQaqNc/edit#

**Comment by kimdhamilton** [comment]
- https://www.w3.org/community/about/faq/#how-do-we-publish-a-report
- https://www.w3.org/community/reports/reqs/

**Comment by kimdhamilton** [comment]
TODO: consider revising work item process:
- human friendly description
- encourage discussion at a higher level

**Comment by kimdhamilton** [comment]
Update: 
- included 7/8 commands and documentation [here](https://github.com/w3c-ccg/w3c-ccg.github.io/blob/master/specs.md)
- TODO: improve new work item guidance as above
- TODO: convert to spectext

**Comment by kimdhamilton** [comment]
Draft here: https://w3c-ccg.github.io/workitem-process/

Propose considering this an ongoing community draft and a working document.

**Comment by vsnt** [comment]
Request to add two additional CCG specific requirements (item 2.1.2) 

1. Non-jargon communication. 
- Answer the Heilmeier Questions: https://www.darpa.mil/work-with-us/heilmeier-catechism
- Identify the primary audience for the work item & how will they use it?

2. Diversity and inclusion. 
- How are you involving participants from multiple skill sets in this work item? (technical, design, product, marketing, anthropological, UX)
- How are you involving participants from various global locations in this work item? (Americas, Euro, Asia-Pacific, South America)
- How do you plan to involve non-technical subject matter experts & end users of your work item? How will you work item improve their lives?
- What actions are you taking to make this work item accessible to a non-technical audience?

**Comment by vsnt** [comment]
Work item participant resources: in order to increase the diversity of work item participants, the CCG will identify & recommend a pool of participants that work item owners can involve in their work items.
- Identify CCG participants that would like to be asked to join new work items & their area of expertise, skill set, etc. (How they want to volunteer)

**Comment by vsnt** [comment]
Peer Leadership
Like peer programming, peer leadership is a leadership planning technique to expose new participant to leadership opportunities without requiring them to take the item on their own. Request to add this as a CCG work item requirement.

- For new work items, the leads should identify someone who has not worked on work items, but would like to, to work on the work item as a mentee/pair work item leader in order to gain experience and confidence.

**Comment by vsnt** [comment]
Propose to close this item, as I have split off three comments that added scope creep to this issue to be tracked on their own.

**Comment by vsnt** [comment]
Propose to close this item. @kimdhamilton - any objections? If none, we will close on Dec 28, 2020.

**Comment by kimdhamilton** [comment]
this is perfect; I'll close it now
