### ISSUE TITLE
Archive functional identity work item?

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#150]
We're in the process of archiving work items that haven't seen activity. This was last updated 2 years ago. https://github.com/w3c-ccg/functional-identity/

Flagging to discuss next meeting.

**Comment by vsnt** [comment]
@jandrieu what is the status of this? Could you reply with 
1. Brief description of the item including the context of the work and what it addresses 
2. Current status, including any blockers 
3. Path to completion, including a realistic timeline

Please reply ASAP. If we do not hear a response within 30 days we will close the work item as incomplete since there has been little work in the past 12 months and it does not look like it is active. Thank you

**Comment by jandrieu** [comment]
I suggest we just close this item. We failed to get sufficient interest in moving it forward.

**Comment by kimdhamilton** [comment]
done
