### ISSUE TITLE
CCG 101 Materials

### ISSUE THREAD

**Issue by vsnt** [w3c-ccg/community#161]
Propose the development of Credentials Community Group 101 materials. The goal is to collect and create materials (written documentation, videos, etc) to help acclimate new participants into both the topics/technology discussed and the processes followed to encourage participation. 

This is likely an ongoing work items with deliverables at certain dates so this is an **ongoing community draft** with final versions of deliverables released as a community report (or video). 

Owners: Heather Vescent: @vsnt & 

Leads: Heather Vescent: @vsnt &

**Comment by wyc** [comment]
Hi Heather, I'd be happy to help as a co-owner on this work item if that works for you.

**Comment by kimdhamilton** [comment]
Phil Long expressed interest in this

**Comment by tkendal** [comment]
LEF is also happy to co-own and invest in this work item in alignment with our broader community outreach efforts.

-Taylor

________________________________

**Comment by vsnt** [comment]
I have recorded two talks that could be good intros. These are currently hosted on the CCG google drive.
1. DID Standardization Activities at the W3C: https://drive.google.com/file/d/1GAxwf7djX1OFeVjf60uRmyTBOhrezXSH/view?usp=sharing
2.  What is Decentralized Identity: https://drive.google.com/file/d/1b5nDHGm6qZv2A4r6QlI0A_nYUtVE4ghF/view?usp=sharing

**Comment by kayaelle** [comment]
This is an excellent topic. I'd like to contribute. 

Off the top of my head: I have a selection of videos about SSI sent to me as part of research. My plan is to view and code/tag. I can publish a table of the results as a reference. This probably won't happen until Dec/Jan.

**Comment by David-Chadwick** [comment]
@vsnt What is Decentralized Identity: https://drive.google.com/file/d/1b5nDHGm6qZv2A4r6QlI0A_nYUtVE4ghF/view?usp=sharing

Unfortunately this presentation mixes up several different concepts (identity, identifier, authenticated login, SSI) and does not compare like with like. The first part (centralised and federated) is actually describing login to an account using an identifier (i.e. username) provided by the IdP, and a password for authentication. In the centralised case the IdP and the resource are the same entity. In the federated case they are different entities. In order to provide a fair comparison with SSI, the final part should do likewise i.e. describe how using verifiable credentials and keys instead of usernames and passwords, a user can login to resources on the Internet. At the conceptual level this has nothing to do with either DIDs or blockchains, but only VCs and keys. Your third part should show the VC model (figure 1 from the standard), with the conceptual shared data repository at the bottom of the figure that is accessible to all three parties (issuer, holder and verifier). You should then say that the user now logs into the resource (the verifier) by presenting a set of VCs issued by the issuers and held in the user's wallet. The VCs identify the user. Proof of possession of the VCs is provided by keys owned/controlled by the user.

Finally if you wish to introduce DIDs and blockchains, which I am sure you do, you can then say that this is just one way of implementing the shared data repository, but there are other ways that do not require either DIDs or blockchains (e.g. web pages, IANA registries, config files, CAs etc.).

I hope this is helpful.

**Comment by vsnt** [comment]
Answering additional work item questions

1. What are you trying to do? Articulate your objectives using absolutely no jargon.
Create materials to introduce processes and technology background for new group participants. They should be accessible to technical and non-technical participants.

2. How is it done today, and what are the limits of current practice?
We don't really have much of these kinds of materials today. We do have the DID Primer and the CCG Process, but these can be more accessible and explained to new participants, as well as other materials to help new group members to get up to speed.

3. What is new in your approach and why do you think it will be successful?
Nothing is really new, but there has been interest in supporting this work to support increased broad participation.

4. Who cares? If you are successful, what difference will it make?
This will 

5. What are the risks?
Scope creep is a risk.

6. How much will it cost?
We have not scoped any budget at this point, other that time and resources. If we want to develop slicker videos or production items, we could create a budget and look for funding. However as suggested, this is a woman-hours/human resources cost.

7. How long will it take?
Unsure at this time. I think we should get the interested parties together to understand what materials are desired to be developed and then put together a project timeline.

8. What are the mid-term and final “exams” to check for success?
These will be built into the project timeline, with CCG meeting check ins. If work is not progressing, we can archive this work item.

9. Identify the primary audience for the work item & how will they use it?
The primary audience is interested parties who have recently joined the CCG.

10. How are you involving participants from multiple skill sets in this work item? (technical, design, product, marketing, anthropological, UX)
Great question. I think we should ask this for the different materials the team decides to develop.

11. How are you involving participants from various global locations in this work item? (Americas, Euro, Asia-Pacific, South America)
This is a great question. It would be good to think about any specific requirements new people from other geographic areas may have. We could do a survey, ask the list, and directly reach out to individuals/communities from outside the Americas.

12. How do you plan to involve non-technical subject matter experts & end users of your work item? How will you work item improve their lives?
We should identify a few people who are willing to beta test our materials, and to review the materials for accuracy.

13. What actions are you taking to make this work item accessible to a non-technical audience?
See answer from #12 to beta test the materials to understand if they are usable.

**Comment by vsnt** [comment]
Approval for this work item went on the wrong issue. Copying it here: 

approved on 17 Nov meeting; @vsnt and @wyc to create using https://w3c-ccg.github.io/create_work_item.html

**Comment by vsnt** [comment]
The work item repo has been created here: https://github.com/w3c-ccg/CCG101

**Comment by kimdhamilton** [comment]
The repo setup looks good, and it's been added to the work items list. Ok to close this
