### ISSUE TITLE
[PROPOSED TASK FORCE] Infrastructure Task Force

### ISSUE THREAD

**Issue by wyc** [w3c-ccg/community#168]
# New Task Force Proposal
See [W3C-CCG New Work Item Process](https://w3c-ccg.github.io/workitem-process/).

## Include Link to Abstract or Draft
This description is WIP. This task force's job is to:
- Manage the CCG's technology inventory, including the teleconferencing system, minutes publishing, `npm` repositories, GitHub actions, cloud services, and budget estimations. 
- Maintain and extend communications capabilities such as teleconferencing to support regular meetings for the weekly meetings, chair meetings, and task force meetings, minimizing issues around availability and reliability.
- Ensure meeting minutes are of high quality and published shortly after our meetings ("shortly" TBD by the task force).
- Maintain and evolve the technical security posture and profile of the CCG to match the desired governance structure of the chairs and the community.
- Create and update documentation so that it always reflects our systems, allowing anyone to join this task force and come up to speed asynchronously.

## Task Force Members
> @wyc (Owner)
> @vmwvmw
> @rhiaro 
> @msporny
> @clehner
> @`{this could be you!!}`

SEEKING CO-OWNERS AND CONTRIBUTORS. REPLY BELOW.

**Comment by vmwvmw** [comment]
Hi everyone! I'm interested in helping out as co-owner of this item.

**Comment by wyc** [comment]
Thanks @vmwvmw, I've added you as a co-owner.

**Comment by rhiaro** [comment]
Thanks for writing this up @wyc, count me in

**Comment by msporny** [comment]
I'm in and volunteer to support the teleconferencing system (infrastructure and code), automatic minute generation (code), root cause analysis on failures, and future-looking improvements like autoscribing, integration with issue tracking, etc.

Digital Bazaar is also committing to at least $1K/year in financial contribution to infrastructure costs.

**Comment by wyc** [comment]
Following @msporny’s example, Spruce Systems commits to $1,000/yr as well.

**Comment by vsnt** [comment]
Would you please answer these questions as part of the proposal process. Thanks.

1. What are you trying to do? Articulate your objectives using absolutely no jargon.
2. How is it done today, and what are the limits of current practice?
3. What is new in your approach and why do you think it will be successful?
4. Who cares? If you are successful, what difference will it make?
5. What are the risks?
6. How much will it cost?
7. How long will it take?
8. What are the mid-term and final “exams” to check for success?
9. Identify the primary audience for the work item & how will they use it? What are secondary audiences?
10. How are you involving participants from multiple skill sets in this work item? (technical, design, product, marketing, anthropological, UX)
11. How are you involving participants from various global locations in this work item? (Americas, Euro, Asia-Pacific, South America)
12. How do you plan to involve non-technical subject matter experts & end users of your work item? 
13. How will you work item improve their lives?
14. What actions are you taking to make this work item accessible to a non-technical audience?
15. Please provide a scope and criteria to conclude the task force?

**Comment by wyc** [comment]
> Would you please answer these questions as part of the proposal process. Thanks.
Sure, please find the answers inlined.
> 
> 1. What are you trying to do? Articulate your objectives using absolutely no jargon.
We are trying to ensure that the CCG's technology is reliable, sustainable, and has clear lines of responsibilities. This technology includes software, servers, cloud services, and online accounts that are required to enable the CCG's critical functions such as meetings, notekeeping, and specific work items.
> 2. How is it done today, and what are the limits of current practice?
It is done ad-hoc, with the responsibility falling upon the chairs and in-the-know community members who already have experience and history building and maintaining the CCG's infrastructure.
> 3. What is new in your approach and why do you think it will be successful?
We are systematizing involvement and delegation of duties with respect to the technology infrastructure. With this work item, we will have committed funds that we haven't had before. This more organized approach estimated to result in a more reliable and maintainable outcome.
> 4. Who cares? If you are successful, what difference will it make?
The entire community will benefit from this common good: this will foster a higher quality of engagement across meetings and support technical dependencies necessary for work items. Notably, the chairs will experience fewer exceptions they must handle and a lower overall amount of work due to delegation, freeing them to pursue higher order initiatives.
> 5. What are the risks?
Assembling volunteers and management of the initiative is the biggest risk, as it is with all such endeavors. Furthermore, we must be careful with security, carefully determining who should have access to what services for purposes of maintenance. This is to be discussed within the task force with ultimate approval by the chairs.
> 6. How much will it cost?
This depends on interest from the community, but mostly work hours, at least 1-2 a week from the work item owners, possibly more in the early days. The total sum cost of IT infrastructure and clouds services to CCG is likely around $1,500/yr.
> 7. How long will it take?
This depends on the level of interest. I estimate 3 months until we establish stable roles and processes. Smaller items such as delegation of note publication can be accomplished far sooner, likely in 2 weeks.
> 8. What are the mid-term and final “exams” to check for success?
Process documents, clear permissioning matrices, chair approval.
> 9. Identify the primary audience for the work item & how will they use it? What are secondary audiences?
The primary audience for the work items produced are the community enjoying the benefits from the work and also members who wish to contribute to this.
> 10. How are you involving participants from multiple skill sets in this work item? (technical, design, product, marketing, anthropological, UX)
We have several entrypoints for folks to contribute, but must spend time identifying these. For example, we welcome folks whether they have a technical background or not to learn how to clean up and publish the minutes.
> 11. How are you involving participants from various global locations in this work item? (Americas, Euro, Asia-Pacific, South America)
We have broadcasted to public-credentials@w3.org about this task force, and most work will occur in the `infrastructure` repo, which allows async communications.
> 12. How do you plan to involve non-technical subject matter experts & end users of your work item?
See answer to 10.
> 13. How will you work item improve their lives?
See answer to 9.
> 14. What actions are you taking to make this work item accessible to a non-technical audience?
Documentation with very clear steps, even for non-technical users.
> 15. Please provide a scope and criteria to conclude the task force?
This task force should continue so long as there is community interest in helping to maintain CCG infrastructure.

**Comment by clehner** [comment]
I'm interested in helping with the technology infrastructure.

**Comment by vsnt** [comment]
Thanks for answering those questions @wyc. I still have concerns about this task force and currently do not support creating it. 

1. Scope Creep
My primary concern is scope creep. It was my understanding this was to stitch up the remaining Jitsi + CCG minutes workflow, which I *think* is now complete. Based on the description, this task force proposes to manage much more. In addition, it adds management overhead through a layer of hierarchy. I'm already seeing issues filed here that IMO don't need the sub-hierarchy.

2. System Audit 
I would appreciate an audit of our internal systems/hosting to understand the scope of needs. How much maintenance is needed for the current systems. At date, this is not clear. This does not have to be detailed documentation, but it needs to be more than we have today. I do not think we need this task force prior to this audit.

3. A Fundamental Technology Attitude
Finally, I have big concerns with a fundamentalist technology attitude that over rides usability by a broader audience. The decision to use Jitsi came from silencing the squeekiest wheels in the community and is not necessarily representative of the community's desires. Additionally, I have low confidence that the members of this proposed task force are aware/sensitive of the obstacles they are placing in order to satisfy their technology fundamentalism. Thus, I foresee a continued obstacle for new participants and presenters. Individuals who are comfortable and support the Jitsi way of doing things have not shown to me a sensitivity or awareness of these biases and the impact they have on people unlike themselves.

There may be a legitimate reason for this task force, however I am not convinced at this time.

**Comment by vongohren** [comment]
Im interessted in helping out with the infrastructure, with the minimal time I have :) I will expectation control things properly if my contributions will falter over time.

**Comment by kimdhamilton** [comment]
@vsnt I recommend you rework #3 to be more fact-based rather than labeling people as "technology fundamentalists". My experience is that inflammatory/attacking language will impede progress.

**Comment by kimdhamilton** [comment]
- @vsnt to update this with latest status. 
- @wyc to send out formal call for objections.

1 week interval for objections, after which can approve (target early next year)

**Comment by vsnt** [comment]
1 & 2: @wyc & I audited the existing system to understand scope & @wyc will get back with his recommendation for the scope. 

3: This objection can not be currently addressed due conflict between the concern and the W3C [strong objection guidelines](https://www.w3.org/2004/02/Process-20040205/policies.html#managing-dissent). It is the opinion of the author that this is an example of masculine default and cultural bias in W3C procedures which does not consider non-strong dissent as valid. 

> Masculine defaults exist when aspects of a culture value, reward, or
> regard as standard, normal, neutral, or necessary characteristics or
> behaviors associated with the male gender role.  ([source](https://depts.washington.edu/sibl/wp-content/uploads/2020/08/Cheryan-Markus-2020-Psychological-Review.pdf))

Thus to have this concern be seriously considered, the author must either take an attitude of strong dissent (which one could argue I have taken) or not have the concern seriously addressed. Since addressing this concern is beyond the scope of the CCG & this group is not responsive to this conversation, the other strong voices & processes prevail.

**Comment by wyc** [comment]
Hi all, 3 weeks ago we proposed the Infrastructure Task Force under the community group. We are evolving as an organization and wish to support a growing number of work items and their requirements, allowing community members to be successful in their efforts. Much of this burden has been shouldered by an ad-hoc patchwork of volunteer effort, personal credit cards, and impromptu work sessions. This is an opportunity to create a clear pathway to involvement and commitment of effort, thus bringing clear expectations and inclusive involvement opportunities to help with these responsibilities.

You can find the proposal here:
https://github.com/w3c-ccg/community/issues/168

I welcome community members to leave feedback in support or opposition as a direct reply to this email thread or within the GitHub issue itself. Without a sustained objection within 7 days, I will move to create this task force.

Best,
- Wayne

**Comment by wyc** [comment]
re: @vsnt 
> 1 & 2: @wyc & I audited the existing system to understand scope & @wyc will get back with his recommendation for the scope.

I reviewed the audit and the current scope. I find the existing scope appropriate. If you have a specific change suggestion, I would be happy to review it. Thank you.

**Comment by kimdhamilton** [comment]
Thank you Kaliya, I agree. 

My opinion is that the Infrastructure Task Force will improve the inclusiveness of the group by separating it from "technical chair" domain (which has also been a single point of failure). As the outgoing chair who has been taking on this responsibility, I believe this is critical for sustainability. 

I'm delighted to see the community eagerly volunteering to take on this work with the additional scope of maintaining open source conferencing system. I think we'll be in good hands with this task force, and enthusiastically support its formation.

**Comment by TallTed** [comment]
I suggest a different naming makes sense.  As I said in a recent call, "Task Force" tends to imply there's a particular, usually relatively limited in scope, "task" that needs doing, for which a "force" needs to be assembled. When the "task" is done, the "force" dissolves.

As I understand the focus of _this_ "Task Force", it feels more like a sub-committee (or perhaps just a committee), or perhaps a sub-group.

From where I sit, it's not about some people having power over others; it's about some people who have time, energy, knowledge (or willingness to learn) in a particular arena, or other resources, who are volunteering to use those resources to deploy and/or maintain some of the tools that let the overall group get our work done (better/faster/more-easily).

As with any group larger than 1 person, there will sometimes be disagreements about the best tool for a particular job. There are certainly competing strengths and weaknesses in all software used here and anywhere else I've ever seen software used. Fairly often, the "least bad" option must be chosen, instead of the "best", and more often, some important feature(s) are not available in the chosen tool, sometimes because these were not considered, sometimes because no known tool sufficiently satisfied all desired features, and sometimes because *other* features were considered more important at that time.

In any case, I believe that concerns which are not "strong objections" should still be raised, and should play a part in the evolution of the group's tools/output. In my 20ish years of working in W3 groups, and 30+ years of working in other groups, I have rarely raised a "strong objection" in the sense of a blocker, but I have often raised concerns which were not blockers and nonetheless were incorporated in the final output. I can't say whether this was due to my personal cis-male-ness or to the strength of my debate points, but I like to think it was the latter.

**Comment by TallTed** [comment]
@wyc -- Yes, that sounds about right.

**Comment by msporny** [comment]
I support the creation of any operating body that reduces the current bus-factor with our infrastructure. It looks like people are willing to step up to support it both from a financial perspective as well as a labor perspective, which is a great sign. I do agree with @vsnt that we need to keep the scope tight on this item and not over extend ourselves or the Chairs. I think it's appropriate to NOT do critical path production stuff (e.g., production npm repositories) until the rest of the infrastructure is more or less fully automated.

**Comment by vsnt** [comment]
@wyc I would like to see a clear scoping document. The audit we did is not a scoping document, but informs the scoping document. 

As @msporny notes above, I would like a tight, limited scope for this nascent entity to show success managing and executing on these items. The devil is in the details and actual execution. I want to see deliverables and accountability.

**Comment by wyc** [comment]
@vsnt here's the scope.

This task force's job is to establish a group to:

- Manage the CCG's technology inventory, including the teleconferencing system, minutes publishing, npm repositories, GitHub actions, cloud services, and budget estimations.
- Maintain and extend communications capabilities such as teleconferencing to support regular meetings for the weekly meetings, chair meetings, and task force meetings, minimizing issues around availability and reliability.
- Ensure meeting minutes are of high quality and published shortly after our meetings ("shortly" TBD by the task force).
- Maintain and evolve the technical security posture and profile of the CCG to match the desired governance structure of the chairs and the community.
- Create and update documentation so that it always reflects our systems, allowing anyone to join this task force and come up to speed asynchronously.

If there is a different format that you'd prefer, could you please show an example of it? I would also appreciate if you took into consideration that this is an entirely volunteer effort, and I likely won't have enough time to fill out a scoping document that is something you'd expect from a professional consultant.

**Comment by kimdhamilton** [comment]
Actually, @vsnt points out an oversight I missed with this proposal, and there are possibly 2 action items to result from this:

1. There has been a (possibly undocumented) expectation that entities like task forces (or whatever this group ends up being) to have a charter. Some notes:
    - They don't have to be very heavy weight, please see the [VC-EDU charter](https://docs.google.com/document/d/1vjrvwmvHOYmJd_Dqwk_TfGjKLTiTe9fzX9J4QqCUcf0/edit#) for an example. 
    - It's important to ensure the charter is readily accessible; so you will likely want to preserve this content outside of this github issue. Note that for VC-EDU, the charter is linked to from the [VC-EDU site](https://github.com/w3c-ccg/vc-ed)
    - We previously didn't have an expectation that charters be in respec, i.e. a google doc or markdown is ok. I'd recommend keeping this lightweight.
2. Because this may be tribal knowledge, we need to check that the work item process captures this.

About the charter format -- there was no template I was able to find. I created the VC-EDU one from looking at other previous task force charters for a model.

**Comment by vsnt** [comment]
@wyc has asked me to extend trust to this entity to get started despite my lack of comfort, and I have done so. So do your best. I am stepping out here and going to focus on places in the CCG where I can make real impact.

**Comment by vsnt** [comment]
@kimdhamilton would you consider adding this tribal knowledge to the draft Task Force FAQ in the chair drive?

**Comment by kimdhamilton** [comment]
done

**Comment by kimdhamilton** [comment]
@vsnt, that's all good, but this still needs a charter :)

**Comment by wyc** [comment]
@kimdhamilton I have prepared a draft of the charter, and would review from yourself and anyone else interested. It is a public document with comments enabled, so happy to take feedback here or there. Thanks!

https://docs.google.com/document/d/1hlP3Vr2OSUxRAcq6i7abn2Z3tWg1Jc7D69yNiL2836Y/edit#

**Comment by kimdhamilton** [comment]
Charter looks great to me

**Comment by TallTed** [comment]
Just a heads up -- I've left a number of change suggestions in the Gdoc, for grammar and clarity and otherwise. I hope they're helpful.

**Comment by vsnt** [comment]
OK with me. I added a todo for you @wyc to add the things you proposed to me in the chair meeting re: leadership and chair veto power.

**Comment by wyc** [comment]
@TallTed Thank you so much for your extensive edits. The document reads much better as a result.

@vsnt Per your request, I have added:
> The community-elected CCG chairs will have final say on the continuation and halting of activities within ITF, determined by a majority vote amongst the chairs. The community elects chairs to be the ultimate accountable members of the CCG membership, so this ensures strong alignment between the ITF with the community interests.

Is this acceptable to folks? cc thread participants, @kimdhamilton @msporny @TallTed @Identitywoman @clehner @rhiaro @vongohren

**Comment by tkendal** [comment]
Apologies if I’m late to the party. I too have made updates and added a few clarifying comments to the charter, which looks great! We (Learning Economy Foundation) would be happy to contribute, particularly as it relates to strengthening the vc-ed TF.

**Comment by vsnt** [comment]
All comments and edits are good by me. Thank you @wyc for your efforts satisfying all concerns and requests.

**Comment by kimdhamilton** [comment]
The addition (quoted below) is unusual in that it doesn’t exist in other “task forces” (which I note we are still classifying this effort as — should we?) 

Curious about the reasons for it. There are possible second order effects/consequences of this addition that would need to be explored if we accept this, but first we should discuss the reasons for the addition, because it may not be necessary 

> The community-elected CCG chairs will have final say on the continuation and halting of activities within ITF, determined by a majority vote amongst the chairs. The community elects chairs to be the ultimate accountable members of the CCG membership, so this ensures strong alignment between the ITF and community interests.

**Comment by wyc** [comment]
@kimdhamilton I am fine removing it, but @vsnt has requested that we add it.

**Comment by wyc** [comment]
@kimdhamilton I am fine to consider its removal, but @vsnt has requested we add it. I can see the argument that people in charge of the facilities and four walls have the possibility of exercising unexpected power, and this could curb such behavior. I think it aims to cover "what if things go wrong and an ITF member goes rogue?"

**Comment by vsnt** [comment]
@kimdhamilton, @wyc suggested this wording to address several of my concerns regarding oversight and decision making. If this text is removed, someone will need to write new text to address chair oversight of this TF.

This proposed TF is different from the other task forces in that they are making decisions about the IT infrastructure of the community group, including financial spending/decision making. In the case of other task forces, I think it would be a best practice to have the CCG chairs address any issues that can not be resolved in the task force itself. But there are obvious differences between say, the confidential storage TF and the infrastructure TF.

@wyc also added this to help me feel comfortable with him moving forward with the task force creation, in order to extend trust to him and this group, even though I am not 100% comfortable.

So if this is removed, we'll have those issues to address again. I personally, am ready to move forward/off this and see what this TF accomplishes. I am holding my breath to judge them based on their actions.

**Comment by kimdhamilton** [comment]
> If this text is removed, someone will need to write new text to address chair oversight of this TF.

This approach (new text to address the specific concerns) sounds preferable because it can list the specific concerns and scope of the veto power. 

As it stands, the scope is open ended and leads  to many other questions — is this language needed for some task forces (again maybe we need to rename this entity) and not others? What might this lead contributors to conclude about the overhead and risks of operating in the ccg?

As a task force lead, the explicit addition of chair veto power, combined with language like below, would make me concerned that my group was viewed with suspicion and perhaps subject to administrative harassment.

> I am holding my breath to judge them based on their actions.

So I prefer @vsnt’s proposal to strike the new language and add text addressing the specific concerns and scope of veto power. I think @vsnt is the only one who can properly speak to these concerns, so let’s have her take a first pass that we can then revise.

(I’ll probably not be checking email/ccg issues for a week or so; either way we should revisit this in the new year, when everyone involved in the task force is also able to comment. Let’s not move forward with that change until then)

**Comment by vsnt** [comment]
@kimdhamilton the text @wyc drafted addressed my specific concerns and he volunteered it, it was not my ask. @wyc would need to draft new text per your request. I am not available to do it and it will not get done if added to my todos. 

The fast way forward is to move forward as is. We are not proposing adding this text to any other task forces. I personally do not want to keep rehashing these issues as it causes me to get angry and again, I am trying to do as @wyc has asked and trust him. I do not think any of us want to drag this out.

**Comment by TallTed** [comment]
re Renaming -- I've said why I think "Task Force" is inappropriate before. Here are a couple of suggested possible new names and abbreviations -- 

* Infrastructure Committee of the Credentials Community Group, CCG-IC
* Technological Infrastructure Committee of the Credentials Community Group, CCG-TIC

-----

Re Governance of this Committee/TaskForce/thing --

We could just say that the Committee can't make decisions, only recommendations, which must be ratified (i.e., Resolved) by the Group as a whole, or by the Chairs alone if the group as a whole deems that sufficient.

Ratification could be based on consensus (as we try to do everything under the W3 umbrella), with fallback (as is typical elsewhere in W3) to majority vote, etc., with ultimate appeal to W3M and/or the Director (again as typical elsewhere W3).

**Comment by kimdhamilton** [comment]
Certainly it’s not a good state if a task force makes a chair angry to the point of being unable to discuss it.

I propose we continue to refine the language to address specific concerns— right now it’s too open ended for me to sign off on. 

Perhaps some time away from this will allow a more amicable discussion of specific objections to this task force, without causing unnecessary anger and stress (which no one wants).

So let’s revisit in the new year. I’m very excited to get this group going in a way everyone is comfortable with, and I do need to hear more from the group members and how they interpret this new language.

**Comment by kimdhamilton** [comment]
+1 to @TallTed’s suggestion, specifically ratification by the Group as a whole (as opposed to chairs only). 

Fallback to w3m is also in our charter I believe, and a good option (We should definitely reconcile it with what’s in our charter to the extent possible)

**Comment by rhiaro** [comment]
Regarding finances of the group, I have come across several projects lately which use [OpenCollective](https://opencollective.com/) (though I don't yet have direct experience with it myself). This lets a group which doesn't have a bank account in its own right sign up to a fiscal host - "fund-holding-as-a-service" - and transparently manage incoming donations and outgoing expense payments. I'm not sure if this ought to be for the CCG as a whole, or only the ITF (my instinct says the former).

The CCG _may_ qualify to be hosted under the [open source](https://opencollective.com/opensource) fiscal host, and I notice [mydata also are a host](https://opencollective.com/mydataorg) though I'm not sure exactly who is behind it. (Alternatively if any of the orgs who have offered funds are able to hold funds on the CGs behalf, they could perhaps set up a fiscal host for us to sign up with.)

Just a thought - I can do more research if folks think it is worth exploring. And it would be valuable to hear from anyone who has already had any experience with OpenCollective.

**Comment by msporny** [comment]
> This lets a group which doesn't have a bank account in its own right sign up to a fiscal host 

We ran a group many years ago called Spec Ops - https://github.com/Spec-Ops and it used a financial host much like OpenCollective. It was a nightmare, for everyone involved... so much so that I never want to be involved in such a book keeping activity ever again. The amount of overhead for processing a simple payment was painful... taking many weeks to months to reimburse contractors. Some contractors just gave up and wrote the work they did off at a loss after months of back-and-forth with the financial host (who has to check every single receipt, every single penny of money going out so they don't lose their tax-free status).

I'm not saying that we shouldn't do it... just that it was *A LOT* of work that resulted in obliterating any tax savings (because of all the extra labor involved) we got by going through the financial host.

My suggestion is that we have a for-profit put their card up to pay the bills, invoice others once a year, and collect payments via Paypal... that's been far easier to manage. We're not talking about a big yearly bill... perhaps only a few thousand dollars or so.

**Comment by rhiaro** [comment]
> It was a nightmare, for everyone involved

Oh yikes, noted. I'm going to try to talk to people who have used OpenCollective specifically because their whole thing is making this as easy as possible (and lots of big open source projects seem to use it) but definitely a no go if it's going to be any kind of headache.

**Comment by msporny** [comment]
> I'm going to try to talk to people who have used OpenCollective

The thing I'm most concerned about is "how does a 'collective' pay for services" -- like, how do we pay our Azure, Twilio, Gandi bills? If it's not by collective credit card, it gets complicated quickly.

**Comment by clehner** [comment]
I've used Open Collective with good experiences, as a contributor (billing for work and being reimbursed for expenses) and admin, e.g. with [Secure Scuttlebutt Consortium](https://opencollective.com/secure-scuttlebutt-consortium/) (@ssbc).

When paying bills, e.g. for domain names and VPS hosting, I would submit an expense for each one, passing the invoice or receipt PDF from the business.

**Comment by msporny** [comment]
> When paying bills, e.g. for domain names and VPS hosting, I would submit an expense for each one

Is there a time limit for submitting expenses? Like, can it be done every quarter year, half year, year?

**Comment by clehner** [comment]
@msporny

> Is there a time limit for submitting expenses? Like, can it be done every quarter year, half year, year?

I think that would be fine. It would be up to the collective. The collective could set a time limit or other expectations in its expense policy.

Another thing to consider is fees. Contributions and payouts may encur a payment processing fee (e.g. 3-5% to PayPal). The fiscal host may also take a fee (5% - unless you are your own fiscal host). And the platform may take a fee (5% - unless you run your own instance).

**Comment by wyc** [comment]
@kimdhamilton @TallTed @vsnt 

I've made some edits to the governance section, would love feedback. Planning to present them later today on our call as well.

> ## Community Governance
> The actions of the ITF are subject to community approval. To ensure a balance between transparency and efficacy, the CCG chairs will first exercise their discretion by majority vote amongst the chairs, and then publicly disclose the decisions immediately after on the public mailing lists.
> 
> While the CCG chairs are expected to exercise their judgement of disclosable actions in the best interests of the community, any member of the ITF may also designate actions as subject to community approval and/or transparency. This is done by disclosing on the public mailing list (1) a summary of the action, (2) who the action affects, and (3) involved parties implementing the action. Because any CCG members may join the ITF, this creates transparency and accountability across its actions.
> 
> After disclosure, community members have the opportunity to review and comment upon the appropriateness of the actions approved or rejected to be taken by the ITF. Community members may also strongly object to decisions. If two or more community members strongly object to the decision, then the matter is to be discussed and then brought forth to the W3C Management team (W3M) for an ultimate decision.
>

**Comment by msporny** [comment]
> then brought forth to the W3C Management team (W3M) for an ultimate decision.

W3M is exceedingly busy and I don't think there is an expectation that they would weigh in on community issues unless it impacts W3C directly. There is a sort of a firewall between W3C CGs and W3C proper (which is different depending on which country you are in) -- W3C proper typically doesn't deal in the affairs of CGs unless there is something that's being transitioned from a CG to an official W3C WG. The line isn't always as well defined as that, but I'd be careful assuming that things can be escalated to W3M.

Have the Chairs talked to W3M about this? I expect they may not be receptive to the idea (but perhaps something has changed internally at W3C since I last spoke w/ them about this)?

**Comment by wyc** [comment]
@msporny thanks for the feedback, I do agree they would likely be adverse to additional burden. Perhaps we could put it up for community vote on the specific action, using the same voting qualifications as for chair voting. I do not anticipate many of these exceptions. Do you have thoughts on this direction?

**Comment by msporny** [comment]
> Perhaps we could put it up for community vote on the specific action, using the same voting qualifications as for chair voting.

Since this would most likely be an exceptional case, yes... we should try to use a consensus process and avoid voting as much as possible. I expect W3M would appreciate that the community deal with their own issues and the community /is/ the final say in any matter (can override the chairs).

**Comment by kimdhamilton** [comment]
+1 to the changes with Manu's corrections. That sounds like the best balance

**Comment by wyc** [comment]
Okay great, and agreed that these should be exceptional cases. I am trying to steer the default mode of acceptance to be consensus-based, but only in the circumstance of 2+ strong objections will we prompt a community vote.

**Comment by wyc** [comment]
Updated the last paragraph:

> After disclosure, community members have the opportunity to review and comment upon the appropriateness of the actions approved or rejected to be taken by the ITF. Community members may also strongly object to decisions. If two or more community members strongly object to the decision within one week after its disclosure, then the matter is escalated to voting by the community to arrive at an ultimate decision, using an identical process for voter qualification and ballots as chair elections.

**Comment by vsnt** [comment]
> Updated the last paragraph:
> 
> > After disclosure, community members have the opportunity to review and comment upon the appropriateness of the actions approved or rejected to be taken by the ITF. Community members may also strongly object to decisions. If two or more community members strongly object to the decision within one week after its disclosure, then the matter is escalated to voting by the community to arrive at an ultimate decision, using an identical process for voter qualification and ballots as chair elections.

Works for me.

**Comment by wyc** [comment]
I will announce a kickoff date by next Wednesday's meeting.

**Comment by wyc** [comment]
I'll be making the repo and sending out a Doodle for a kickoff meeting.

**Comment by wyc** [comment]
Hi all, could you please indicate your availability if you're interested in the kick-off?

https://doodle.com/poll/aghvr4p32c58xzyu

**Comment by wyc** [comment]
Created here:

https://github.com/w3c-ccg/infrastructure
