### ISSUE TITLE
[PROPOSED WORK ITEM] Vaccination Certificate Vocabulary

### ISSUE THREAD

**Issue by tplooker** [w3c-ccg/community#182]
# New Work Item Proposal

A work item to define a vocabulary for issuing vaccination certificates in the form of Verifiable Credentials.

## Include Link to Abstract or Draft 

Draft Spec - https://w3id.org/vaccination
GH Repo - https://github.com/mattrglobal/vaccination-certificate-vocab/

## List Owners

@tplooker

**Comment by OR13** [comment]
I would be happy to support / edit this vocabulary... I'd love to help provide JSON Schema like we have done for https://github.com/w3c-ccg/traceability-vocab

**Comment by mprorock** [comment]
We would absolutely be willing to engage and support this initiative.  We have a definite use case surrounding food processing worker validation as well as farmer worker validation

**Comment by AdamJLemmon** [comment]
Love it @tplooker ! 
We're working with healthcare providers in Singapore to issue Vaccination Certificates (Healthcerts) and be great to collaborate on a unified vocab.

**Comment by wyc** [comment]
I personally welcome this work item, and commend that it's focused on defining a concrete shared vocabulary instead of an overbroad framework that may not work for everyone.

To move forward, is someone willing to step up as a co-owner of this item, as per the [CCG work item process](https://w3c-ccg.github.io/workitem-process/#additional-ccg-requirements)?

**Comment by jstclair2019** [comment]
Be happy to contribute as well! I think we discussed this somewhere? :)

**Comment by mprorock** [comment]
Absolutely willing to step up as a co-owner

Mike Prorock
CTO, Founder
https://mesur.io/

**Comment by cstoecker** [comment]
We love this work a lot as well and would like to contribute to the work item. We would like to help with the JSON LD schema and some testing / test vectors ... potentially in a similar way as @OR13 is referring to in the traceability vocab. 

We started doing a MVP for a field test via retrofitting of existing Doctor Office SW ... so that a doctor can issue a Vaccination Credential via API integration of his software / patient appointment management system and his Vaccination Credential Issuance Module (aka Doctor Wallet). We are planning to use W3C Verifiable Credential featuring Ed25519 Digital Signatures. 

We developed a basic **vaccination schema** in accordance to Recommendations of the [EU Health Network](https://ec.europa.eu/health/sites/health/files/ehealth/docs/vaccination-proof_interoperability-guidelines_en.pdf). The data structure of the EU Health Network work item is very, very similar to the CCI work. 

There is only one difference. EU Health Network recommends to include an *optional Person Identifier*: "An identifier of the vaccinated person, according to the policies applicable in each country. It should be captured what type of identifier is used. Examples: citizen ID card or identifier within the health system/IIS/e-registry".

**Comment by tplooker** [comment]
Thanks all for the feedback, looking forward to the collaboration, thanks @mprorock and @OR13 for offering to be co-owners, I will start by updating the spec to include you, however welcome contributions from as many people willing. @wyc after this is complete what is the next step?

**Comment by vsnt** [comment]
@tplooker next step is for the chairs to create the repo.

**Comment by tplooker** [comment]
@vsnt last time I contributed a work item I believe we actually transferred it instead, keeps the GH level links working, I will have to update the w3id setup once transfered though to prevent a double redirect.

**Comment by wyc** [comment]
@tplooker is the repo name as `w3c-ccg/vaccination-certificate-vocab` fine with you?

**Comment by OR13** [comment]
I would prefer the shorter `vaccination-vocab`

**Comment by wyc** [comment]
@tplooker is `w3c-ccg/vaccination-vocab` okay with you? Upon confirmation, I will promptly transfer your repo from https://github.com/mattrglobal/vaccination-certificate-vocab/

**Comment by tplooker** [comment]
Yeap ok with me

**Comment by wyc** [comment]
Thanks @tplooker, please find the repo here: https://github.com/w3c-ccg/vaccination-vocab

The owners are @tplooker, @OR13, and @mprorock.

I have opened two issues which once resolved should allow your work item to fulfill CCG requirements.

**Comment by wyc** [comment]
Closing this issue, please re-open if you need further assistance.

**Comment by pknowl** [comment]
I would also suggest that the VCV folks include the "Certificate metadata" attributes from the eHealth Network (EU) proof of vaccination specification. That spec contains those additional attributes, which would be a great blueprint for a generic vaccine credential form. Search for "Certificate metadata" in the eHealth specification for more details.

I'm leading the CCI Schema Task Force at CCI / LF Public Health. We're currently in the process of developing a global schema specification for COVID-19 vaccine capture. I've attached an early draft. I thought that it might help re your efforts at W3C.
[COVID-19_vaccination_capture.xlsx](https://github.com/w3c-ccg/community/files/6040779/COVID-19_vaccination_capture.xlsx)
