### ISSUE TITLE
DID resolution specification

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#20]
This needs to be done with coordination with DIF.

An was opened against the DID spec regarding DID document versioning. The CCG decided (todo: link to minutes when available) that this concept belongs in the methods specs, but should also be addressed across method specs for interoperability. For example, not all method specs will support a version number, but those that do should be able to align.

https://github.com/w3c-ccg/did-spec/issues/64

This brings up the general question of method spec metadata alignment. 

We propose a specification for the DID resolver; since the implementation  is being worked on by DIF, we will coordinate with them

**Comment by peacekeeper** [comment]
+1 to creating a DID resolver specification, I'd love to work with @dmitrizagidulin and others on this. From a logistics point of view, to get started, would it be as simple as creating a new repo in the CCG? @pelle may also be interested since he implemented a JS resolver, and I know that in the BTCR hackathons there were also some discussions e.g. about how to include resolver metadata.

The DIF resolver has a few wiki pages e.g. [here](https://github.com/decentralized-identity/universal-resolver/blob/master/docs/api-definition.md) and [here](https://github.com/decentralized-identity/universal-resolver/blob/master/docs/architecture-drivers.md), but those are not in great shape.

**Comment by msporny** [comment]
> From a logistics point of view, to get started, would it be as simple as creating a new repo in the CCG?

Yes, it would be that simple.

We need to check with @csuwildcat to make sure we're not stomping on any toes here. The understanding is that CCG works on specs, and DIF works on implementations... so the DID Resolver spec would be a CCG work item, while the development on DID Resolvers continues at DIF. @csuwildcat, does that work for you?

**Comment by peacekeeper** [comment]
@dmitrizagidulin and I had a call and we created a new repo for this: https://w3c-ccg.github.io/did-resolution/

**Comment by msporny** [comment]
Making sure that @csuwildcat saw what @peacekeeper and @dmitrizagidulin are working on. I'm trying to make sure that no one gets surprised by how all this work is progressing.

**Comment by csuwildcat** [comment]
I don't have any issue with the actual SDO specs being done in W3C, as DIF does not intend to be the end body for doing SDO spec formalization and passage. I would still like DIF to remain a center of gravity for development of implementations and engineering deliverables, if that makes sense to the folks on the thread.

**Comment by kimdhamilton** [comment]
TODO @kimdhamilton: officially kick off as a work item

**Comment by awoie** [comment]
> Here's the information needed to officially propose:
> 
> * Draft: https://w3c-ccg.github.io/did-resolution/
> * Owner: @peacekeeper (?)
> * Sponsors:
>   
>   * Confirmed: @dmitrizagidulin @kimdhamilton
>   * TBD: @mitfik @awoie
> 
> TODO @kimdhamilton: related and included in scope is DID test suites, so we'll need a related repo. Is this a separate work item?

@kimdhamilton @peacekeeper Yes, I am also interested to be involved in the spec.

**Comment by kimdhamilton** [comment]
setup complete
