### ISSUE TITLE
Complete update to RSA Signature Suite spec

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#3]
~@msporny I can help with this~
Narrator: she didn’t 
Let’s get a new volunteer or assign to someone Manu delegates

^ @ChristopherA

**Comment by ChristopherA** [comment]
Almost a year later — what is the status on this spec? If no progress or report, we will close this work item in 30 days.

**Comment by Cahl-Dee** [comment]
Factom Inc is willing to allocate resources to support this effort. This is critical for our implementation within Android mobile apps as the secure enclave on Android, known as [Hardware-backed Keystore](https://source.android.com/security/keystore), does not support ED25519 which we typically use and therefore have chosen to go with RSA. 

[Supported key types ref](https://source.android.com/security/keystore/implementer-ref#generate_key).

Since this issue is within the CCG Github org, I believe the scope is with regard to the RSA section of the [Linked Data Cryptographic Suite Registry](https://w3c-ccg.github.io/ld-cryptosuite-registry/#rsa). Is that correct?

I would like to confirm since on the call the DVCG GitHub org was brought to my attention and I'm seeing an [RSA Signature Suite 2018](https://w3c-dvcg.github.io/lds-rsa2018/) there. I'd go as far as to suggest that this issue cover the consolidation of the two.

**Comment by msporny** [comment]
> Factom Inc is willing to allocate resources to support this effort.

Digital Bazaar is willing and happy to support Factom in this effort. We can answer any questions that you may have when updating this specification.

**Comment by ChristopherA** [comment]
@Cahl-Dee @msporny — can we get update on the status of this work item? Any ETA?

**Comment by msporny** [comment]
@Cahl-Dee has left Factom, and I'm slammed w/ DID WG and SDS WG work.

**Comment by OR13** [comment]
Recommend archiving / marking as deprecated and pointing to https://github.com/w3c-ccg/lds-jws2020

**Comment by OR13** [comment]
I have added a readme / warning / archived: 

https://github.com/w3c-ccg/lds-rsa2018

I suggest closing this issue.

**Comment by msporny** [comment]
> Recommend archiving / marking as deprecated and pointing to https://github.com/w3c-ccg/lds-jws2020

If we're going to do this, I have deep concerns around how JWS2020 is planning on being used (to express private keys in DID Documents, too much variability, etc.). Just noting this as I've been avoiding having that discussion to date to let the suite get a bit further... but if we're at the point where we need to debate some of the security implications of lds-jws2020, we should put aside some telcon time to do it.

**Comment by OR13** [comment]
@msporny 

If there is an active RSA only suite which we can point to that does not support the other JWK/JWS/JWE stuff, that would 100% be better to point to....its my understanding that there is not one.

Yes, we should have a call to sync on it... especially regarding support for JWE, which seems to be a clear driving force for alignment with JOSE in DIDComm and Encrypted Data Vaults... 

I know at least these folks have some experience with this topic @troyronda @kdenhartog, @tplooker and @kimdhamilton @csuwildcat @selfissued have had some comments on it.

Maybe it would be wise for us to take some time to debate this on an upcoming CCG call?

**Comment by kimdhamilton** [comment]
Recommend closing this and open new issue to track Manu's concern.

**Comment by OR13** [comment]
Agree, issues should track work that we believe will happen, and focus on enabling community members to take that action.

This seems like a feature request for RSASignature2020... suite that uses RSA but not JOSE.

I'd rather see that as a separate issue.

**Comment by kimdhamilton** [comment]
Discussion will happen in a DID special topic call -- is it for legacy, etc? Next week. Outcome will be made public, and we can discuss here

**Comment by kimdhamilton** [comment]
8/11: any remaining thing we're tracking here? It's been 2 years. I'd like to close this.

**Comment by kimdhamilton** [comment]
per 8/11 discussion, we'll close this. Please create a new, more specific issue if any concerns above were not addressed.
