### ISSUE TITLE
Review CCG Github Editors List at EOY

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/community#34]
Need to edit https://github.com/orgs/w3c-ccg/teams/editors/members to reflect editors of current work items, and do this at least yearly (maybe sub-task of creating EOY list for future CCG chairs).

**Comment by kimdhamilton** [comment]
TODO: this is connected to the CODEOWNERS file

**Comment by kimdhamilton** [comment]
I grepped CODEOWNERS and ensured they were present in the Editors team. I removed everyone else from the Editors team except those in the column "NOT LISTED IN CODEOWNERS". This set of (5) people I left because they are/have been actively contributing to a variety of specs.

What do we think about this?


| ﻿ALIAS            | NAME                      | EDITORS | NOT LISTED IN CODEOWNERS | CHAIRS |
|------------------|---------------------------|---------|--------------------------|--------|
| @burnburn        | Daniel Burnett            | x       | x                        |        |
| @ChristopherA    | Christopher Allen         | x       |                          | x      |
| @cwebber         | Christopher Lemmer Webber | x       |                          |        |
| @David-Chadwick  | David Chadwick            | x       | x                        |        |
| @dlongley        | Dave Longley              | x       |                          |        |
| @dmitrizagidulin | Dmitri Zagidulin          | x       |                          |        |
| @jandrieu        | Joe Andrieu               | x       |                          | x      |
| @kimdhamilton    | Kim (Hamilton) Duffy      | x       |                          | x      |
| @mikelodder7     | Michael Lodder            | x       | x                        |        |
| @msporny         | Manu Sporny               | x       |                          |        |
| @peacekeeper     | Markus Sabadello          | x       |                          |        |
| @rhiaro          | Amy Guy                   | x       | x                        |        |
| @stonematt       | Matt Stone                | x       | x                        |        |
| @talltree        | Drummond Reed             | x       |                          |        |

**Comment by kimdhamilton** [comment]
Per discussion with chairs, we're approving of leaving in the state described in previous comment. Closing
