### ISSUE TITLE
Discuss registries meta-process; what are next steps?

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#75]
Manu documented a registries meta process here:
https://lists.w3.org/Archives/Public/public-credentials/2017Dec/0020.html

Does this roll it into the new work item process, or is it a separate work item?

**Comment by kimdhamilton** [comment]
Check minutes of last meeting to determine what we decided with this

**Comment by kimdhamilton** [comment]
Modifications per chair discussion:
- Has to be proposed by specification editor (from WG or CCG spec) 
- Has to have at least 2 editors to review
- If process becomes compromised, at the discretion of editors we may close the registry
- No unreleased phase, no final phase

**Comment by kimdhamilton** [comment]
Important resource: https://www.w3.org/wiki/Registries

**Comment by kimdhamilton** [comment]
Looking for person to lead

**Comment by kezike** [comment]
Responding to the comment from @kimdhamilton on 6/20 in an attempt to understand the needs of this issue:

> Modifications per chair discussion:
> 
> * Has to be proposed by specification editor (from WG or CCG spec)
  - Does this suggest that the registries can only be proposed by spec editors?
> * Has to have at least 2 editors to review
  - How are these editors chosen? Is it just the first to volunteer or will there be a more formal process for this?
> * If process becomes compromised, at the discretion of editors we may close the registry
  - Please elaborate on your meaning of "process becomes compromised".
> * No unreleased phase, no final phase
  - Please elaborate. Does this mean that there will be no staging and that registries will just be published immediately after the editor review process?

General Questions:
- What is the primary goal of this work around registries?
- What inspired this discussion in general?
- According to Manu's 12/9/2017 proposal, "[t]here has been an increasing desire to externalize the DID Methods, Linked Data Key Types, and Credential Status Methods out of the
core Verifiable Credentials and DID Method specs." Isn't this the kind of work we are seeing with the DID Method Registry (https://w3c-ccg.github.io/did-method-registry/)?
- What implementation requirement model are we aiming for (refer to section "Requirements on implementations" of https://www.w3.org/wiki/Registries in order to understand this question)

**Comment by kimdhamilton** [comment]
AB has provided a draft proposal that seems like a solid foundation:

https://w3c.github.io/w3process/registries/#registries

**Comment by jandrieu** [comment]
It would be great if current CCG registry editors could review that proposal and give feedback.

**Comment by kimdhamilton** [comment]
@msporny @talltree and tbd others: any feedback?

**Comment by kimdhamilton** [comment]
See tracking issue: https://github.com/w3c/w3process/issues/168

**Comment by ChristopherA** [comment]
WG-Process did not move this forward completion in the 2020 process. Instead, registry issues have been moved to a 2021 process milestone. https://github.com/w3c/w3process/milestone/6

**Comment by jandrieu** [comment]
Also: https://github.com/w3c/w3process/issues/168#issuecomment-597444116

**Comment by kimdhamilton** [comment]
is this good enough? See last section https://docs.google.com/document/d/1vj811aUbs8GwZUNo-LIFBHafsz4rZTSnRtPv7RQaqNc/edit#heading=h.i2v9iagxg4em

**Comment by kimdhamilton** [comment]
ok to close?

**Comment by ChristopherA** [comment]
Will review at next CCG meeting. Community should read https://docs.google.com/document/d/1vj811aUbs8GwZUNo-LIFBHafsz4rZTSnRtPv7RQaqNc/edit#heading=h.i2v9iagxg4em and any comments on this should be brought up a new issues.

**Comment by wyc** [comment]
This was completed as part of the @w3c-ccg/workitem-process.
