### ISSUE TITLE
Revisit doc to spectext conversion tool if that format is required for work items

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#76]
In the interest of making work item processes more friendly to non-tech folks, we can consider revisiting Sandro's conversion tool. We'd need a (tech) volunteer to look into this

**Comment by BillBarnhill** [comment]
Per the call, I am happy to volunteer, pending finding out what language it's coded in (I can muddle through with many of the major ones). Do we want to schedule an IRC call to discuss this further, or would people prefer to discuss in the issue's comments? 

Also, what's the URL to the repository for the tool, or is it under the w3c-ccg repo?

**Comment by BillBarnhill** [comment]
Answered my own question, with some digging. Recommend we clone this repo into w3c-ccg. Also, can I get added to the w3c-ccg committers group please?

URLs:
- Example doc:  [https://credweb.org/report/](https://credweb.org/report/)
- Generated at: [https://github.com/w3c/credweb/tree/master/report](https://github.com/w3c/credweb/tree/master/report)
- The re-usable code: [https://github.com/sandhawke/gdoc2respec](https://github.com/sandhawke/gdoc2respec)

Source:  https://lists.w3.org/Archives/Public/spec-prod/2018JulSep/0003.html

**Comment by kimdhamilton** [comment]
Perfect; I just found it myself but you beat me to it. I'll add you as a committer.

**Comment by BillBarnhill** [comment]
As an update, I've been looking at this but haven't has a lot of time over the last couple weeks. I've noticed a couple things that need to change regarding how it builds, and noticed it creates extra empty paragraphs. I'm also exploring an alternative approach using Google Docs API. I'll have more progress to report next week.

**Comment by kimdhamilton** [comment]
Also review: https://github.com/w3c-dvcg/http-signatures-test-suite/tree/add-template-reporter/implementations

**Comment by aljones15** [comment]
the above one is for Implementation tests

1. Custom Mocha Reporter collects results of tests.
2. Result of mocha reporter is then formatted to a handlebars.js file.

This is a really different use case then the google doc conversion tool however
it does programmatically create Sections and could be abstracted to use a json object
that in turn becomes an html spec.

**Comment by kimdhamilton** [comment]
```
git clone https://github.com/tabatkins/bikeshed.git
cd src/misc/bikeshed
pip install --editable ~/<location>/bikeshed
```

**Comment by BillBarnhill** [comment]
Using markdown would allow us to edit directly on Github as well, which won't provide a WYSIWYG editor but does have a preview. It also would version-control the changes in Git. 

Google doc comments might be missed, but comments can be done in a pull request.  Also

The biggest downside I see for the markdown and bikeshed approach is non-devs won't know Git, but basic Git use is something we should be able to help people overcome. 

A way to overcome the need to install Python and bikeshed would be if the W3C or one of the members ran Web server (or Amazon lambda) providing a Github hook triggered on changes of a file with a name matching a template (e.g., *.bs). This hook could:

1. Pull the changes onto a local clone of a 'bikeshedding' branch 
2. Run Bikeshed on the file to produce the new version of the respec document locally
3. Commit changed respec document and push to 'bikeshedding' branch on Github
4. Use Github API to issue pull request for the changes. This extra step is for security, in case service gets hacked or there's an error and bikeshed fails to produce the correct respec

**Comment by BillBarnhill** [comment]
### Observations from gdocs2respec review

* gdoc2respec requires the doc to be publicly viewable. 
* gdoc2respec performs parsin using a combination of  Cheerio (a lighter weight JQuery implementation) and regex matching
* The Google Docs API's export endpoint does preserve comments in the exported HTML, The HTML is minified though, and I noticed the following results from gdoc2respec:
   * produces a number of extra empty para tag pairs(&lt;p>&lt;/p>), and sometimes other empty tag pairs (e.g., &lt;b>&lt;/b>)
   * does not combine bolded spans into one &lt;b>&lt;/b>
   * ignores some formatting, such as underlining, font size changes

### Using Google Docs

We could use gdoc2respec, if we can accept the above limitations. 

Otherwise we could use the Google Docs API to retrieve the document as JSON and create the respec document from the JSON data model.  The Google Docs API would also allow export of a non-public read-accessible doc, using their OAUTH API. I have the start of this already, but it's complex due to handling all the formatting and model complexity, so it's not complete.

Using Google Docs still has the issue that the process to generate the respec would be a barrier to non-devs (installing Node, cloning the repository, running the build script), so a member of the CCG with some dev experience would need to run the script, or we would need to automate it.

### Recommendation

I like Kim's proposed approach using Github and Bikeshed over either Google Docs approach. I think the concerns can be mitigated with some combination of a good tutorial and automation.

**Comment by kimdhamilton** [comment]
Added instructions here:
https://w3c-ccg.github.io/bikeshed_instructions.html

I propose to close after discussing at next meeting

**Comment by BillBarnhill** [comment]
I'm good with closing. Do we want to create a separate issue for standing
up something automated, to make it easier for non-developers to contribute?
Something along the lines of server-side Git hooks (supported by Github and
Gitlab) that trigger a server-side Bikeshed pipeline resulting in the
server pushing a commit of the new version of the Bikeshed output respec to
Gitlab or Github repo.  Fairly easy to do with Amazon lambda free tier,
with no server needed from W3C.

**Comment by kimdhamilton** [comment]
closing per above
