### ISSUE TITLE
Name VCWG Maintenance Mode github repo

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#93]
From 10/29 meeting, there is an action to name VCWG Maintenance Mode github repo
[https://w3c-ccg.github.io/meetings/2019-10-29/#action-1](https://w3c-ccg.github.io/meetings/2019-10-29/#action-1)

**Comment by kimdhamilton** [comment]
@ChristopherA nag the assignees on the 12/3 call

**Comment by msporny** [comment]
We need to create a repo to track VCWG Maintenance Mode WG concerns as they relate to the CCG.

**Comment by msporny** [comment]
Just created: https://github.com/w3c-ccg/vcwg-maintenance

**Comment by burnburn** [comment]
@msporny we need to discuss.  We want proposed modifications to the data model spec to be able to move fairly simply into PRs in the WG

**Comment by msporny** [comment]
> @msporny we need to discuss. We want proposed modifications to the data model spec to be able to move fairly simply into PRs in the WG

Agreed, PRs and issues on specific specs should be raised in those repos... everything else can go in the github repo.

**Comment by burnburn** [comment]
> Agreed, PRs and issues on specific specs should be raised in those repos... everything else can go in the github repo.

I disagree somewhat.  The goal was to have vetted, consolidated PRs appear in the WG repos - not ones that are to be individually discussed in the WG.  But maybe we can handle that by specially marking those PRs that are actually ready for the WG to give their thumbs up/down.  As I said, we need to discuss.

**Comment by kimdhamilton** [comment]
closing

**Comment by msporny** [comment]
@burnburn wrote:
> I disagree somewhat. The goal was to have vetted, consolidated PRs appear in the WG repos - not ones that are to be individually discussed in the WG. But maybe we can handle that by specially marking those PRs that are actually ready for the WG to give their thumbs up/down. As I said, we need to discuss.

Hey @burnburn, I saw this during the call yesterday but was hopelessly distracted to give you a good response. Yes, the CCG should discuss how this happens because we don't want the danger you outlined... VCWG needs clear PRs w/ CCG approval.

The repo I created is merely for things that don't clearly fall into the spec repo buckets, such as meta questions about notes that might benefit from VCWG publication, or cross-cutting issues that clearly don't belong in a VCWG spec repo, etc.

Perhaps we should get a more complete, less hand-wavy proposal together that we can put in front of the CCG for consideration. Here's a first cut at one:

1. All VCWG spec related issues should be raised in the appropriate specification repository. CCG should engage in those issues in the spec repository.
2. All issues that result in PRs on a VCWG spec MUST be reviewed, gain consensus, and be approved by CCG before consideration by VCWG. All PRs on VCWG specs must be clearly labeled as having CCG consensus.
3. All issues and PRs that do not fall into the category above, but do pertain to VCWG specifications, should go in the https://github.com/w3c-ccg/vcwg-maintenance for further discussion.

Not tied to any of those points, just trying to start the conversation.
